# Generated by Django 5.1.2 on 2024-12-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serialNumber', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('datePurchased', models.DateField()),
                ('qr', models.ImageField(blank=True, null=True, upload_to='assets/qrs/')),
                ('state', models.CharField(choices=[('available', 'Available'), ('damaged', 'Damaged'), ('retired', 'Retired')], default='available', max_length=20)),
            ],
        ),
    ]
