# Generated by Django 5.1.2 on 2024-12-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serialNumber',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
